"""
Step 8: assemble esg_pillars/report.md from the results CSVs already
written by 02_analysis.py. No new estimation here.

Run:  python3 esg_pillars/03_report.py
"""

import pandas as pd

primary = pd.read_csv("esg_pillars/results_primary.csv")
secondary = pd.read_csv("esg_pillars/results_secondary_joint.csv")
corr = pd.read_csv("esg_pillars/results_pillar_correlations.csv", index_col=0)
vif = pd.read_csv("esg_pillars/results_vif.csv")

lines = []
lines.append("# E/S/G Pillar Check — Exploratory Analysis\n")
lines.append(
    "**Exploratory.** This is a post-hoc breakdown of the paper's main ESG-disclosure measure "
    "into its three pillars, run once, not pre-registered, and not currently part of the paper's "
    "reported results. Modeled on the one-pillar-per-regression approach in Brasch & Eckert "
    "(2024, *Risk Management and Insurance Review* 27, 313-329) — with the pillar *definition* "
    "necessarily different, see the scope note below. Scripts and full numeric output live in "
    "`esg_pillars/`; this file is generated by `03_report.py` from the results CSVs, not "
    "hand-transcribed.\n"
)

lines.append("## Step 1 — Data availability (checked before building anything)\n")
lines.append(
    "Sentence-level E/S/G labels **do exist** — `env_flag`, `soc_flag`, `gov_flag` are "
    "independent binary flags per sentence (ESG-BERT multilabel classification, CEO-letters "
    "notebook cell 40's `esg_multilabel()`), available for every sentence, not just ESG-flagged "
    "ones.\n\n"
    "**But Table 5a's richer measures cannot be split by pillar without inventing a "
    "classification.** `Corporate_ESG_share`, `Verified_ESG_share`, and `Specificity_mean` all "
    "depend on a GPT specificity/corporate-relevance classification that was only ever run two "
    "ways: E alone (Section 6.11) and **S+G combined** (Section 6.12, explicitly filtered as "
    "`(soc_flag==1 OR gov_flag==1) AND env_flag==0`). Social and Governance were never classified "
    "separately at that level — the corpus was pooled by design. Building `Corporate_S_share` or "
    "`Verified_G_share` would require commissioning new GPT classification runs split by S and G, "
    "which was explicitly out of scope for this check.\n\n"
    "**What this analysis actually uses:** the simpler `ESG_sentence_ratio` definition (Table "
    "5a's Model 1 baseline: pillar-flagged sentences ÷ total sentences per firm-year), split by "
    "dimension. This is a real, unmodified measure already available from the raw ESG-BERT flags "
    "— not an invented one — but it is a **narrower** measure than the Corporate/Verified/"
    "Specificity-restricted pillar breakdown a reader might expect from a Brasch & Eckert-style "
    "table. If the richer version is wanted, the missing piece is new S-only and G-only GPT "
    "specificity classification (mirroring Sections 6.11/6.12's existing pipeline, split "
    "further), not anything this script can produce from existing data.\n"
)

lines.append("## Step 2 — Reproduction\n")
lines.append(
    "`01_reproduce.py` independently rebuilt Table 5a (Q as DV) from the same raw pre-lag export "
    "used in `null_check/`, merged in the E/S/G pillar ratios, and confirmed **all six Table 5a "
    "coefficients reproduce within tolerance** before any pillar model was fit. Zero firm-years "
    "were lost to the pillar merge (0 of 209 missing an E/S/G ratio) — the pillar export and the "
    "main panel cover exactly the same firm-year set.\n"
)

lines.append("## Correlations among the pillars\n")
lines.append(
    "Pairwise correlations among the (lagged) E/S/G ratios, full merged panel:\n\n"
    + corr.round(3).to_markdown() + "\n\n"
    "All three pairwise correlations are low (0.15-0.20) — the pillars are not simply "
    "interchangeable proxies for the same underlying disclosure intensity, though the shared "
    "positive sign across all three pairs suggests a modest common driver (e.g. overall CEO "
    "letter length/verbosity) alongside pillar-specific variation.\n"
)

lines.append("## Steps 3-4 — Primary: six pillar-alone models\n")
lines.append(
    "Each pillar's one-year-lagged sentence ratio, fit alone (not jointly with the other two "
    "pillars), same controls/FE/HC3-robust SEs and the same `build_model_sample()` per-model "
    "complete-case + firm-count guard as Table 5a. This is the primary specification, matching "
    "Brasch & Eckert's one-pillar-per-regression approach.\n"
)
main_cols = ["dv", "spec", "coef", "se", "ci_lo", "ci_hi", "p_raw", "n"]
lines.append(primary[main_cols].round(4).to_markdown(index=False))
lines.append("\n")
lines.append(
    "### Standardized effects, MDE, and TOST classification (informative null / inconclusive / significant)\n"
)
std_cols = ["dv", "spec", "std_coef", "std_ci_lo", "std_ci_hi", "mde_std_80pct_power",
            "equiv_within_0.10SD", "equiv_within_0.20SD", "classification"]
lines.append(primary[std_cols].round(4).to_markdown(index=False))
lines.append("\n")

lines.append("## Step 5 — Multiple-testing correction across the six primary tests\n")
lines.append(primary[["dv", "spec", "p_raw", "p_holm", "p_bh"]].round(4).to_markdown(index=False))
lines.append("\n")
lines.append(
    "No raw p-value was below 0.05 to begin with (smallest is p=0.368, `S alone` on `Q`), so "
    "both Holm and Benjamini-Hochberg leave every adjusted p-value at or near 1 — the correction "
    "changes nothing substantive here, but is reported in full as requested rather than skipped "
    "because it \"obviously wouldn't matter.\"\n"
)

lines.append("## Step 7 — Secondary (labeled): joint three-pillar model\n")
lines.append(
    "All three pillars entered together in one model, one per outcome. **Secondary check only "
    "— not the primary specification** (see Step 3-4 above for that).\n"
)
lines.append(secondary[["dv", "term", "coef", "se", "ci_lo", "ci_hi", "p_raw", "n"]]
             .round(4).to_markdown(index=False))
lines.append("\n### VIF (joint models, FE dummies excluded from the VIF matrix)\n")
lines.append(vif.round(3).to_markdown(index=False))
lines.append("\n")
lines.append(
    "All VIFs are low (max 2.32, on `Leverage` — a control, not a pillar; the three pillar "
    "lags themselves are all ≤1.18). **No collinearity concern**, consistent with the low "
    "pairwise correlations above.\n\n"
    "**Comparison to the primary (pillar-alone) models:** every joint-model coefficient stays "
    "the same sign as its pillar-alone counterpart, and no pillar crosses the p<0.05 threshold "
    "in either specification — the joint model doesn't change the substantive conclusion for any "
    "pillar/outcome pair. Coefficients shrink slightly in the joint model for E and G (S stays "
    "essentially flat), consistent with the small positive correlations among the pillars "
    "absorbing a little of each other's explanatory content, not with any pillar's effect being "
    "an artifact of omitting the other two.\n"
)

lines.append("## Honest summary\n")
lines.append(
    "**Five of six primary tests are informative nulls within ±0.10 SD; the sixth "
    "(`S alone` → `Q`) is an informative null only at the looser ±0.20 SD bound, not tighter.** "
    "Unlike the earlier `null_check/` result on the combined ESG measures — where the headline "
    "`Corporate_ESG_share` term (Model 3) failed to establish equivalence even at ±0.20 SD — "
    "every pillar here is at least loosely informative. That's a real difference worth noting: "
    "**this particular breakdown does not reproduce a hidden large effect** that the combined "
    "measure was somehow diluting. If anything, this adds modest weight to the combined-measure "
    "null being a real absence of a strong signal, not just underpowering — though \"modest,\" "
    "not decisive, since these pillar measures are the narrower sentence-ratio definition (Step "
    "1), not the same richer measure that showed the wider CI in `null_check/`.\n\n"
    "**Do not read \"5 of 6 informative nulls\" as strong confirmation of no effect.** All MDEs "
    "here (0.08-0.16 SD at 80% power) are themselves not tiny — this design still cannot rule "
    "out small-to-moderate pillar-specific effects with high confidence, it can only rule out "
    "*larger* ones. And this whole analysis uses a genuinely different (narrower) pillar "
    "definition than the paper's headline `Corporate_ESG_share`/`Verified_ESG_share` measures, so "
    "it is evidence about *sentence-ratio* E/S/G disclosure, not a pillar decomposition of the "
    "paper's actual headline result.\n"
)

lines.append("## Assumptions and judgment calls (flagged per instruction)\n")
lines.append(
    "1. **Pillar definition is narrower than Table 5a's combined measures** — sentence ratio "
    "(matches Model 1), not Corporate/Verified/Specificity-restricted. See Step 1. This is the "
    "single most important caveat on this whole analysis.\n"
    "2. **Primary vs. secondary framing** — pillar-alone models treated as primary (per "
    "instruction, matching Brasch & Eckert's approach); joint three-pillar model treated as a "
    "secondary robustness check, not given equal billing.\n"
    "3. **Standardization convention** — same partial-standardized-effect convention as "
    "`null_check/` (coef × SD(x)/SD(y) on each model's own complete-case sample).\n"
    "4. **z, not t, critical values** — matches this codebase's HC3 output convention "
    "(`P>|z|`), negligible difference at this sample size (df≈147-148).\n"
    "5. **TOST bounds (±0.10/±0.20 SD)** were specified directly in the request, not chosen by "
    "me.\n"
    "6. **VIF/collinearity check scope** — computed on the joint model's own design matrix "
    "(pillars + controls), FE dummies excluded (same convention as `null_check/`, since "
    "categorical FE mechanically inflates VIF regardless of real collinearity).\n"
    "7. **Multiple-testing correction applied across exactly the six primary tests** (not "
    "including the two secondary joint-model coefficients per pillar, which would double the "
    "family and change the corrected thresholds) — a defensible but not the only reasonable "
    "choice of test family.\n"
)

with open("esg_pillars/report.md", "w") as f:
    f.write("\n".join(lines))

print("Wrote esg_pillars/report.md")
